name: mz_raport
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Scientific Computing and Data Analysis
  - numpy>=1.21.0        # Fundamental package for scientific computing
  - pandas>=1.3.0        # Data manipulation and analysis library
  - matplotlib>=3.4.0    # Plotting and visualization library
  - seaborn>=0.11.0      # Statistical data visualization based on matplotlib
  
  # Testing
  - pytest>=6.2.5        # Python testing framework
  
  # Development Tools
  - python-dotenv>=0.19.0  # Environment variable management
  - black>=21.5          # Python code formatter
  - flake8>=3.9.2        # Python code linter
  - isort>=5.9.1         # Python import sorter
  
  # Jupyter Environment
  - jupyter              # Interactive notebook environment
  - ipykernel           # IPython kernel for Jupyter
  
  # Package Management
  - pip                  # Python package installer

