name: mz_raport
channels:
  - conda-forge
  - defaults
dependencies:
  - black[version='>=21.5']
  - flake8[version='>=3.9.2']
  - ipykernel
  - isort[version='>=5.9.1']
  - jupyter
  - matplotlib[version='>=3.4.0']
  - numpy[version='>=1.21.0']
  - pandas[version='>=1.3.0']
  - pip
  - pytest[version='>=6.2.5']
  - python-dotenv[version='>=0.19.0']
  - python=3.9
  - seaborn[version='>=0.11.0']
  - openpyxl
  - geopandas
  - unidecode
  - chardet
  - fuzzywuzzy

